### ISSUE TITLE
No llena el formulario si le das 2 veces al mismo sugestion

### ISSUE THREAD

**Issue by ernesto-butto** [poolebu/ebookme#106]
Hay que darle al tab de ebookme para que lo haga

**Comment by laslorma** [comment]
se agrego la propiedad `cache:false` en la definicion del state y `reload:true` en la llamada del state.go , para que se pudiera re-ejecutar el controller con la segunda llamada a un suggestion

**Comment by laslorma** [comment]
pr  #124
