### ISSUE TITLE
correcciones pagina ebookme

### ISSUE THREAD

**Issue by laslorma** [poolebu/ebookme#121]
- [x] 1- Agregar logos de google play y paypal en el header de la pagina, en una misma fila del lado derecho
- [x] 2.- una vez lita corrija los banners, cambiar el tercer banner de primero y el primero de tercero
- [ ] 3.- agregar banners creando los estilos y layouts necesarios para agregar los textos lo mas parecido al diseño . ( es decir no subir los banner solo como imagenes)

**Comment by fpestana** [comment]
Asumo que los logos de google play son los que estan en la pagina. El donate y el link directo a ebookme! Asi: [image](https://cloud.githubusercontent.com/assets/11448562/13970612/11c92eea-f05c-11e5-92d9-a56129242ecd.png)

Los de abajo se quitaran?

El logo lo tuve que colocar a la izq porque ya no quedaba bien centrado

**Comment by fpestana** [comment]
![image](https://cloud.githubusercontent.com/assets/11448562/13971091/7f225e32-f05f-11e5-8bd1-bc15a1677e1f.png)

**Comment by fpestana** [comment]
Coloque el link de la aplicacion en el campo app_linkbar_url, de manera que pueda cambiarse con diferentes aplicaciones.  

Este es es update para asignarlo
`UPDATE `catw_mt_angular_1`.`application` SET `application_linkBar_url` = 'https://play.google.com/store/apps/details?id=io.catwizard.ebookme2' WHERE `application`.`app_list_id` = 57;`

**Comment by fpestana** [comment]
Insert para el nuevo template:
`INSERT INTO `catw_mt_angular_1`.`template` (`template_id`, `template_name`, `template_html_file_name`, `template_css`) VALUES (NULL, 'template-ebookme.html', 'template-ebookme.html', NULL);`

Al crear el nuevo template dividi la parte final en dos columnas directamente en el template para no hacerlo en el codigo de la pagina. Lo habia realizado asi porque estaba reutilizando uno existente pero al crear uno para esta sección entonces es mejor que se adapte mas sin tanto codigo de grid en el txt-control.

Entonces, para asignar el nuevo template a ebokme, se TIENE que modificar la ultima parte de la sección para que se vea bien.

La tercera parte de este ticket la creare en otro para poder cerrar este y dar como finiquitardo una parte de la actualizacion.

Los cambios en el orden de los banners ya se hizo en la version online.

**Comment by fpestana** [comment]
PR:https://github.com/laslorma/Catwizard/pull/1454
