### ISSUE TITLE
Agregar campo de titulo a la interfaz

### ISSUE THREAD

**Issue by ernesto-butto** [poolebu/ebookme#25]
agregar validaciones de formulario , todos los casos son requeridos

**Comment by laslorma** [comment]
done PR #32

**Comment by laslorma** [comment]
se intento implementar el modulo para ngMessages, el cual permite centralizar los mensajes para los formularios, pero no se logro hacer funcionar el include del template de errores.

https://docs.angularjs.org/api/ngMessages
http://www.gajotres.net/ionic-framework-tutorial-10-form-handling-and-validation/
