### ISSUE TITLE
Guardar para hacer auto complete los correos utilizados en el pasado

### ISSUE THREAD

**Issue by ernesto-butto** [poolebu/ebookme#56]
Puede ser como JSONS en el local storage

Es fastidioso tener que volver a meter todo el correo

**Comment by laslorma** [comment]
http://learn.ionicframework.com/formulas/localstorage/

ngStorage with ionic
https://medium.com/@petehouston/awesome-local-storage-for-ionic-with-ngstorage-c11c0284d658#.z4nfykazc

https://github.com/gsklee/ngStorage#usage

**Comment by laslorma** [comment]
se decidio agregar un componente de lista, en donde se mostraran los email que han sido guardados en localstorage , y al hacer click el usuario en uno de ellos lo vera en el campo de texto de email del formulario. es una especie de autocomplete

**Comment by laslorma** [comment]
agrega guardar en local storage emails usados
no se hace la validacion del email ya que se presenta un problema con el binding del model, si se agrega el ng-pattern el binding se hace despues de que la validacion es correcta, si no lo es no, por lo quea el filter que permite la busqueda del correo en la lista de correos guardados en storage no funciona visualmente bien. Se acordo hacer la validacion en el backend, faltaria una vez hecho esto agregar el respectivo mensaje en el fronend

**Comment by laslorma** [comment]
done # #66
