### ISSUE TITLE
Bug Suggestion y reset

### ISSUE THREAD

**Issue by fpestana** [poolebu/ebookme#82]
Voy a Suggestion, selecciono uno de ellos y lo trae al form ok.
Si le doy clic a reset borra todo, Ok. 
Voy otra vez a Suggestion y selecciono nuevamente el que seleccione antes. En este caso me lleva al form pero no me trae ningun valor del suggest. (si lo vuelvo hacer sigue pasando)
Vuelvo a suggest y selecciono otro. Lo trae sin problema. 
Le doy a reset borra todo.
Vuelvo a suggest y selecciono el sug otra vez y no me trae nada, intento otra vez con el primero que seleccione y tampoco me trae nada y asi con todos los sug. 

En ocasiones al darle a reset me abre la ventana para escoger el formato pero es a veces no encuentro un patron pa que salga.

**Comment by laslorma** [comment]
corregido en #106
