### ISSUE TITLE
Mandar informacion a lita para diseno. Ver descripcion

### ISSUE THREAD

**Issue by ernesto-butto** [poolebu/ebookme#95]
Estructura de la pagina, slider con instrucciones, contenido tipo el del store, boton al play store, boton donate

mail de lita: Lita Candela litacandela@gmail.com

**Comment by laslorma** [comment]
Dani, cuando le envies la info a Lita , hazlo a traves de la app de soporte RT, de esa forma todos vemos la conversacion que se genere y queda en el historial todos los recursos compartidos etc

![highreswithalpha_con_fondo](https://cloud.githubusercontent.com/assets/11031593/13367572/a30e0e9e-dcb5-11e5-8aa4-0a4814bf7b63.png)
